detectors:
  UtilityFunction:
    exclude:
      - 'options'
      - 'FileHelper'
  IrresponsibleModule:
    exclude:
      - 'BasePage'
      - 'SignInPage'
      - 'SignUpPage'
      - 'TopMenuSection'
      - 'User'
      - 'IssuesPage'
      - 'ProjectsPage'
      - 'SpentTimePage'
      - 'CommonVars'
  TooManyInstanceVariables:
    max_instance_variables: 10
  TooManyStatements:
    max_statements: 20
  DuplicateMethodCall:
    exclude:
      - 'FeatureHelper'
  FeatureEnvy:
    exclude:
      - 'APIWrapper'
  TooManyConstants:
    exclude:
      - 'CommonVars'